// Actual tabCapture + both local models. Invoke the native toolbar and Start.
import assert from "node:assert/strict";
import { execFileSync, spawn } from "node:child_process";
import { once } from "node:events";
import { createHash } from "node:crypto";
import { mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { createServer } from "node:http";
import { resolve } from "node:path";
import { createInterface } from "node:readline";
import { chromium } from "playwright";
import { traceCaptionPaints } from "./caption-paint.mjs";

const mode = process.argv[2];
assert.ok(mode === undefined || ["before", "after", "stream", "overlap", "lifecycle"].includes(mode));
const lifecycle = mode === "lifecycle";
const overlap = mode === "overlap";
const streaming = mode === "stream" || overlap;
const paintPhase = streaming || lifecycle ? undefined : mode;
const instrumented = !!paintPhase || streaming || lifecycle;
const metrics = [];
const interruptions = [];
let finishTrace;
let paintReport;
let lineBuffer = "";

await mkdir(".ralph", { recursive: true });
const profile = await mkdtemp(resolve(".ralph/local-browser-"));
execFileSync("say", ["-v", "Samantha", "-r", "165", "-o", `${profile}/speech.aiff`,
  "The weather is sunny today. We will walk to the park after lunch."]);
execFileSync("afconvert", ["-f", "WAVE", "-d", "LEI16@24000", "-c", "1", `${profile}/speech.aiff`, `${profile}/speech.wav`]);
const audio = await readFile(`${profile}/speech.wav`);
const clips = [];
if (instrumented) {
  const sentences = streaming
    ? ["Bring a blue umbrella and a warm coat, and meet at the station at three in the afternoon for our trip.",
      ...(overlap ? ["It is sunny."] : [])]
    : ["The weather is sunny today.", "We will walk to the park after lunch."];
  for (const [index, text] of sentences.entries()) {
    execFileSync("say", ["-v", "Samantha", "-r", "165", "-o", `${profile}/${index}.aiff`, text]);
    execFileSync("afconvert", ["-f", "WAVE", "-d", "LEI16@24000", "-c", "1", `${profile}/${index}.aiff`, `${profile}/${index}.wav`]);
    clips.push(await readFile(`${profile}/${index}.wav`));
  }
}
const fixture = createServer((request, response) => {
  if (request.url === "/speech.wav") { response.setHeader("Content-Type", "audio/wav"); response.end(audio); return; }
  const clip = clips[Number(request.url?.match(/^\/([01])\.wav$/)?.[1])];
  if (clip) { response.setHeader("Content-Type", "audio/wav"); response.end(clip); return; }
  response.setHeader("Content-Type", "text/html");
  response.end(`<!doctype html><html lang="en"><meta charset="utf-8"><title>Local speech acceptance</title>
    <style>body{margin:0;background:#446879;color:white;font:24px system-ui}main{padding:48px}audio{width:80%}</style>
    <main><h1>Generated English speech</h1><p>A non-sensitive weather and park sentence, generated by macOS.</p>
    <audio controls src="/speech.wav"></audio><button id="play">Play speech</button></main>
    <script>document.querySelector('#play').onclick=()=>{const a=document.querySelector('audio');a.currentTime=0;a.play()};</script></html>`);
});
let context;
let companion;
let input;
let log = "";
let passed = false;
let stopped = false;
let failed = false;
let measured = false;
let tabId;
try {
  await new Promise((ready) => fixture.listen(8766, "127.0.0.1", ready));
  const extension = resolve("extension/dist");
  context = await chromium.launchPersistentContext(profile, {
    channel: "chromium", headless: false, viewport: { width: 1280, height: 800 },
    args: [`--disable-extensions-except=${extension}`, `--load-extension=${extension}`],
  });
  const worker = context.serviceWorkers()[0] ?? await context.waitForEvent("serviceworker");
  const extensionId = new URL(worker.url()).host;
  companion = spawn("uv", ["run", "--locked", "--extra", "local", "uvicorn", instrumented ? "browser_metrics:app" : "server.app:app",
    "--app-dir", instrumented ? "tests" : ".",
    "--host", "127.0.0.1", "--port", "8765", "--ws-max-size", "4096", "--ws-max-queue", "8"], {
    env: { ...process.env, PYTHONPATH: ".", INTERPRETER_EXTENSION_ID: extensionId,
      INTERPRETER_PAINT_BASELINE: paintPhase === "before" ? "1" : "0",
      INTERPRETER_LIFECYCLE_METRICS: lifecycle ? "1" : "0",
      HF_HUB_OFFLINE: "1", TRANSFORMERS_OFFLINE: "1" },
    stdio: ["ignore", "pipe", "pipe"],
  });
  companion.stdout.on("data", (chunk) => {
    if (!instrumented) { log += chunk; return; }
    lineBuffer += chunk;
    let end = lineBuffer.indexOf("\n");
    while (end >= 0) {
      try { const metric = JSON.parse(lineBuffer.slice(0, end)); if (metric.metric) metrics.push(metric); } catch {}
      lineBuffer = lineBuffer.slice(end + 1); end = lineBuffer.indexOf("\n");
    }
  });
  companion.stderr.on("data", (chunk) => { log += chunk; });
  await new Promise((ready, reject) => {
    const timeout = setTimeout(() => reject(new Error(`Companion startup timed out: ${log}`)), 20000);
    companion.once("error", reject);
    companion.stderr.on("data", () => {
      if (log.includes("Uvicorn running")) { clearTimeout(timeout); ready(); }
    });
  });
  const page = context.pages()[0];
  await page.goto("http://127.0.0.1:8766/");
  if (instrumented) {
    tabId = await worker.evaluate(async (url) => (await chrome.tabs.query({})).find((tab) => tab.url === url)?.id, page.url());
    assert.ok(tabId);
    await worker.evaluate((id) => chrome.scripting.executeScript({ target: { tabId: id }, files: ["content.js"] }), tabId);
    finishTrace = await traceCaptionPaints(context, page, worker, tabId);
  }
  if (streaming) {
    await page.setViewportSize({ width: 270, height: 700 });
    await worker.evaluate((id) => chrome.scripting.executeScript({ target: { tabId: id }, func: () => {
      // Ephemeral generated text stays in the browser; the report contains no transcript.
      globalThis.streamViews = [];
      let observer;
      function record() {
        const cue = document.querySelector("#interpreter-captions")?.shadowRoot?.querySelector(".cue");
        const text = cue?.textContent;
        if (!text) return;
        // A queued caption's arrival does not mean its text is already visible.
        const view = globalThis.streamViews.findLast((v) => v.translation.includes(text));
        if (!view || text === view.parts.at(-1)?.text) return;
        const box = cue.getBoundingClientRect();
        const atMs = performance.timeOrigin + performance.now();
        const part = { text, atMs, offset: view.translation.indexOf(text), length: text.length,
          twoLines: cue.clientHeight <= Number.parseFloat(getComputedStyle(cue).lineHeight) * 2 + 9 };
        view.parts.push(part);
        performance.mark(`interpreter-caption:${JSON.stringify({
          sessionId: view.sessionId, utteranceId: view.utteranceId, revision: view.revision,
          final: view.final, type: "part", atMs, offset: part.offset, length: part.length,
          twoLines: part.twoLines, visible: true, left: box.left, right: box.right, top: box.top, bottom: box.bottom,
        })}`);
      }
      chrome.runtime.onMessage.addListener((message, sender) => {
        if (sender.id !== chrome.runtime.id || message.target !== "captions" || message.type !== "caption") return;
        globalThis.streamViews.push({ ...message.caption, receivedAtMs: performance.timeOrigin + performance.now(), parts: [] });
        const cue = document.querySelector("#interpreter-captions")?.shadowRoot?.querySelector(".cue");
        if (!cue) return;
        if (!observer) {
          observer = new MutationObserver(record);
          observer.observe(cue, { childList: true, characterData: true, subtree: true });
        }
        record();
      });
    } }), tabId);
  }
  console.log(JSON.stringify({ ready: true, browser: context.browser().version(), extensionId,
    mode, profile, instructions: "Native Extensions toolbar → Interpreter → Start; close popup. Lifecycle: interrupt → native Start → recover → replace → native Start → recover → lifecycle-report → native Stop → stopped → exit. Other modes: overlap, long, measure, play, check, accept, stopped, exit." }));
  input = createInterface({ input: process.stdin });
  for await (const command of input) {
    try {
      if (command === "exit") break;
      if (command === "interrupt" || command === "replace") {
        assert.ok(lifecycle);
        assert.equal(interruptions.length, command === "interrupt" ? 0 : 1);
        if (command === "replace") assert.ok(interruptions[0].recovery);
        const { captureStatus } = await worker.evaluate(() => chrome.storage.session.get("captureStatus"));
        assert.equal(captureStatus.state, "capturing");
        const popupUrl = `chrome-extension://${extensionId}/popup.html`;
        // A real popup document handles Stop/configure; it never initiates capture.
        const created = await worker.evaluate((url) => chrome.tabs.create({ url, active: false }), popupUrl);
        let popup;
        try {
          const deadline = Date.now() + 90000;
          popup = context.pages().find((p) => p.url() === popupUrl);
          while (!popup) {
            assert.ok(Date.now() < deadline, "No real popup document");
            await page.waitForTimeout(20);
            popup = context.pages().find((p) => p.url() === popupUrl);
          }
          await popup.locator("#stop:enabled").waitFor();
          const start = metrics.length;
          await page.locator("audio").evaluate(async (element) => { element.src = "/0.wav"; await element.play(); });
          const underway = () => metrics.slice(start).find((m) => m.sessionId === captureStatus.sessionId
            && (command === "interrupt" ? m.metric === "asr.start" : m.metric === "caption" && !m.final));
          while (!underway()) {
            assert.ok(Date.now() < deadline, "No actual inference in progress");
            await page.waitForTimeout(10);
          }
          const actionAtMs = Date.now();
          if (command === "interrupt") await popup.locator("#stop").click();
          else await popup.locator('[name="provider"]').selectOption("luna");
          await popup.locator('#status[data-state="idle"]').waitFor();
          const idleAtMs = Date.now();
          const captured = await worker.evaluate(() => chrome.tabCapture.getCapturedTabs());
          const offscreen = await worker.evaluate(() => chrome.runtime.getContexts({ contextTypes: ["OFFSCREEN_DOCUMENT"] }));
          assert.ok(!captured.some((tab) => tab.status === "active"));
          assert.equal(offscreen.length, 0);
          assert.equal(await page.locator("#interpreter-captions").count(), 0);
          if (command === "replace") {
            const saved = await worker.evaluate(() => chrome.storage.local.get("sessionSettings"));
            assert.equal(saved.sessionSettings.provider, "luna");
            await popup.locator('[name="provider"]').selectOption("local");
            await popup.waitForFunction(async () => (await chrome.storage.local.get("sessionSettings")).sessionSettings.provider === "local");
          }
          const sample = { action: command, sessionId: captureStatus.sessionId, underwayAtMs: underway().atMs,
            actionAtMs, idleAtMs, offscreenContexts: 0, captionHosts: 0, activeCapturedTabs: 0 };
          interruptions.push(sample);
          console.log(JSON.stringify({ interrupted: sample, next: "Native toolbar Start, close popup, then recover" }));
        } finally {
          if (popup) await popup.close();
          else await worker.evaluate((id) => chrome.tabs.remove(id), created.id);
          await page.bringToFront();
        }
      }
      if (command === "recover") {
        assert.ok(lifecycle);
        const sample = interruptions.at(-1);
        assert.ok(sample && !sample.recovery);
        const { captureStatus } = await worker.evaluate(() => chrome.storage.session.get("captureStatus"));
        assert.equal(captureStatus.state, "capturing");
        assert.notEqual(captureStatus.sessionId, sample.sessionId);
        const start = metrics.length;
        await page.locator("audio").evaluate(async (element) => { element.src = "/1.wav"; await element.play(); });
        const deadline = Date.now() + 90000;
        while (!metrics.slice(start).some((m) => m.metric === "caption" && m.final && m.sessionId === captureStatus.sessionId)) {
          assert.ok(Date.now() < deadline, "No replacement-session real final");
          await page.waitForTimeout(20);
        }
        const translated = await page.locator("#interpreter-captions .cue").textContent();
        console.log(JSON.stringify({ review: sample.action, translated }));
        assert.match(translated, /점심/); assert.match(translated, /공원/); assert.match(translated, /(?:걷|산책|걸)/);
        await page.waitForTimeout(100);
        sample.recovery = { sessionId: captureStatus.sessionId, qualityChecks: true,
          finalAtMs: metrics.slice(start).find((m) => m.metric === "caption" && m.final).atMs };
        console.log(JSON.stringify({ recovered: sample.recovery }));
      }
      if (command === "lifecycle-report") {
        assert.ok(lifecycle && finishTrace);
        assert.equal(interruptions.length, 2);
        assert.ok(interruptions.every((s) => s.recovery));
        const rows = await finishTrace(); finishTrace = undefined;
        for (const sample of interruptions) {
          const old = metrics.filter((m) => m.sessionId === sample.sessionId);
          const disconnect = old.find((m) => m.metric === "disconnect");
          const end = old.find((m) => m.metric === "session.end");
          assert.ok(disconnect && end);
          const asrStart = old.filter((m) => m.metric === "asr.start" && m.atMs <= sample.underwayAtMs).at(-1);
          assert.ok(asrStart);
          const asrEnd = old.find((m) => m.metric === "asr.end" && m.atMs > asrStart.atMs);
          assert.ok(asrEnd);
          if (sample.action === "interrupt") assert.ok(asrEnd.atMs > disconnect.atMs,
            "Stop must happen before actual native inference completes");
          else assert.ok(!old.some((m) => m.metric === "caption" && m.final && m.atMs > asrStart.atMs),
            "Provider change must interrupt translation before its final");
          assert.ok(!old.some((m) => m.metric === "caption" && m.atMs >= disconnect.atMs));
          assert.ok(!rows.some((r) => r.sessionId === sample.sessionId && r.type === "caption" && r.atMs >= sample.idleAtMs));
          const nextStart = rows.find((r) => r.type === "start" && r.sessionId === sample.recovery.sessionId);
          assert.ok(nextStart);
          assert.ok(!rows.some((r) => r.type === "caption" && r.sessionId === sample.sessionId && r.atMs >= nextStart.atMs));
          const final = rows.find((r) => r.type === "caption" && r.sessionId === sample.recovery.sessionId && r.final);
          assert.ok(final?.paintAtMs !== null && final?.paintAtMs !== undefined);
          Object.assign(sample, { disconnectAtMs: disconnect.atMs, sessionEndAtMs: end.atMs,
            nativeAsrStartAtMs: asrStart.atMs, nativeAsrEndAtMs: asrEnd.atMs,
            noLateCaption: true, recoveryFinalPaintAtMs: final.paintAtMs });
        }
        const preparations = metrics.filter((m) => m.metric === "prepare.start").map((start, index) => {
          const end = metrics.find((m) => m.metric === "prepare.end" && m.sessionId === start.sessionId);
          const ready = metrics.find((m) => m.metric === "ready" && m.sessionId === start.sessionId);
          assert.ok(end && ready);
          return { sessionId: start.sessionId, firstPreparation: index === 0,
            startAtMs: start.atMs, endAtMs: end.atMs, readyAtMs: ready.atMs,
            prepareMs: end.atMs - start.atMs, readyMs: ready.atMs - start.atMs };
        });
        assert.equal(preparations.length, 3);
        const receipts = metrics.filter((m) => m.metric === "receipt");
        const report = { browser: context.browser().version(), nativeCapture: true, realLocalModels: true,
          captureStarts: "native toolbar Start on the fixture for each session; Stop/configure via real popup document automation",
          speech: "macOS Samantha 165 wpm; weather then park after lunch", wavSha256: clips.map((c) => createHash("sha256").update(c).digest("hex")),
          preparations, interruptions, trace: rows,
          maxPendingAudioMs: Math.max(0, ...receipts.map((r) => r.pendingAudioMs)),
          droppedFrames: Math.max(0, ...receipts.map((r) => r.droppedFrames)),
          droppedUtterances: Math.max(0, ...receipts.map((r) => r.droppedUtterances)),
          timingLimit: "cached weights; preparation-to-ready excludes native click/offscreen creation, no cold-cache comparison",
          listening: "not verified; UI tools expose no speaker audio" };
        assert.ok(report.maxPendingAudioMs <= 8000);
        assert.equal(report.droppedFrames, 0); assert.equal(report.droppedUtterances, 0);
        await writeFile("docs/verification/latency/lifecycle.json", `${JSON.stringify(report, null, 2)}\n`);
        console.log(JSON.stringify(report));
        measured = true; passed = true;
      }
      if (command === "overlap") {
        assert.ok(overlap && finishTrace && tabId);
        const { captureStatus } = await worker.evaluate(() => chrome.storage.session.get("captureStatus"));
        assert.equal(captureStatus.state, "capturing");
        const samples = [];
        for (let repetition = 0; repetition < 3; repetition++) {
          const start = metrics.length;
          await page.locator("audio").evaluate(async (element) => { element.src = "/0.wav"; await element.play(); });
          const deadline = Date.now() + 90000;
          while (!metrics.slice(start).some((m) => m.metric === "caption" && m.final)) {
            assert.ok(Date.now() < deadline, "No actual long final");
            await page.waitForTimeout(10);
          }
          // The second real phrase starts while the first final still has unread parts.
          await page.locator("audio").evaluate(async (element) => { element.src = "/1.wav"; await element.play(); });
          while (metrics.slice(start).filter((m) => m.metric === "caption" && m.final).length < 2
            || await page.locator("#interpreter-captions").count()) {
            assert.ok(Date.now() < deadline, "Overlapping actual captions did not complete/expire");
            await page.waitForTimeout(20);
          }
          const [{ result: views }] = await worker.evaluate((id) => chrome.scripting.executeScript({
            target: { tabId: id }, func: () => globalThis.streamViews,
          }), tabId);
          const finals = metrics.slice(start).filter((m) => m.metric === "caption" && m.final);
          assert.equal(finals.length, 2);
          const finalViews = finals.map((m) => views.find((v) => v.utteranceId === m.utteranceId && v.final));
          const [long, short] = finalViews;
          console.log(JSON.stringify({ review: repetition, finals: finalViews.map((v) => ({
            source: v.source, translation: v.translation, parts: v.parts.map((p) => p.text) })) }));
          assert.match(long.source.toLowerCase(), /blue umbrella/); assert.match(long.source.toLowerCase(), /warm coat/);
          assert.match(long.source.toLowerCase(), /station/); assert.match(long.source.toLowerCase(), /three.*afternoon/);
          assert.match(long.source.toLowerCase(), /trip/);
          assert.match(long.translation, /(?:파란|파랑|푸른).*우산/); assert.match(long.translation, /따뜻한.*(?:코트|외투)/);
          assert.match(long.translation, /역/); assert.match(long.translation, /오후.*(?:3시|세 시)/); assert.match(long.translation, /여행/);
          assert.match(short.source.toLowerCase(), /sunny/); assert.match(short.translation, /(?:맑|화창)/);
          assert.ok(long.parts.length > 1);
          const secondArrival = views.find((v) => v.utteranceId === short.utteranceId).receivedAtMs;
          assert.ok(secondArrival < long.parts[1].atMs, "The next real caption must precede the unread long part");
          for (const final of finalViews) {
            assert.equal(final.parts.map((p) => p.text).join(""), final.translation.trim());
            assert.ok(final.parts.every((p) => p.twoLines));
            assert.doesNotMatch(final.translation, /[\u3040-\u30ff]/u);
          }
          samples.push({ repetition, sessionId: captureStatus.sessionId, firstInference: repetition === 0,
            nextCaptionAtMs: secondArrival, unreadPartAtMs: long.parts[1].atMs,
            finals: finalViews.map((v) => ({ utteranceId: v.utteranceId, revision: v.revision,
              characterCount: v.translation.trim().length, qualityChecks: true, allCharactersDisplayed: true,
              parts: v.parts.map(({ text, ...part }) => part) })) });
        }
        const rows = await finishTrace(); finishTrace = undefined;
        for (const sample of samples) for (const final of sample.finals) {
          const parts = rows.filter((r) => r.type === "part" && r.utteranceId === final.utteranceId && r.revision === final.revision);
          assert.equal(parts.length, final.parts.length);
          assert.ok(parts.every((p) => p.paintAtMs !== null), "Every final part needs a covering Chromium Paint");
          final.parts = parts;
        }
        const receipts = metrics.filter((m) => m.metric === "receipt" && m.sessionId === captureStatus.sessionId);
        const report = { browser: context.browser().version(), nativeCapture: true, realLocalModels: true,
          speech: "macOS Samantha 165 wpm; umbrella/coat/station/trip, followed by sunny weather", viewport: page.viewportSize(),
          wavSha256: clips.map((c) => createHash("sha256").update(c).digest("hex")), samples,
          maxPendingAudioMs: Math.max(0, ...receipts.map((r) => r.pendingAudioMs)),
          droppedFrames: receipts.at(-1)?.droppedFrames, droppedUtterances: receipts.at(-1)?.droppedUtterances,
          listening: "not verified; UI tools expose no speaker audio" };
        assert.ok(report.maxPendingAudioMs <= 8000);
        assert.equal(report.droppedFrames, 0); assert.equal(report.droppedUtterances, 0);
        await writeFile("docs/verification/latency/stream-overlap.json", `${JSON.stringify(report, null, 2)}\n`);
        console.log(JSON.stringify(report)); measured = true; passed = true;
      }
      if (command === "long") {
        assert.ok(streaming && finishTrace && tabId);
        const { captureStatus } = await worker.evaluate(() => chrome.storage.session.get("captureStatus"));
        assert.equal(captureStatus.state, "capturing");
        const samples = [];
        for (let repetition = 0; repetition < 3; repetition++) {
          const start = metrics.length;
          await page.locator("audio").evaluate(async (element) => { element.src = "/0.wav"; await element.play(); });
          const deadline = Date.now() + 90000;
          while (!metrics.slice(start).some((m) => m.metric === "caption" && m.final)) {
            assert.ok(Date.now() < deadline, "No real long final before deadline");
            await page.waitForTimeout(50);
          }
          await page.waitForTimeout(100);
          await page.screenshot({ path: `docs/verification/latency/stream-long-${repetition}.png` });
          // Wait for every timed part of the real final, including its expiry.
          while (await page.locator("#interpreter-captions").count()) {
            assert.ok(Date.now() < deadline, "Long cue did not expire");
            await page.waitForTimeout(50);
          }
          const [{ result: views }] = await worker.evaluate((id) => chrome.scripting.executeScript({
            target: { tabId: id }, func: () => globalThis.streamViews,
          }), tabId);
          const finals = metrics.slice(start).filter((m) => m.metric === "caption" && m.final);
          assert.equal(finals.length, 1, "This generated phrase must form one complete utterance");
          const revisions = views.filter((v) => v.sessionId === captureStatus.sessionId && v.utteranceId === finals[0].utteranceId);
          const final = revisions.find((v) => v.final);
          assert.ok(final);
          const translated = final.translation;
          console.log(JSON.stringify({ review: repetition, source: final.source, translation: translated,
            displayedParts: final.parts.map((part) => part.text) }));
          assert.match(final.source.toLowerCase(), /blue umbrella/);
          assert.match(final.source.toLowerCase(), /warm coat/);
          assert.match(final.source.toLowerCase(), /station/);
          assert.match(final.source.toLowerCase(), /three.*afternoon/);
          assert.match(final.source.toLowerCase(), /trip/);
          assert.match(translated, /(?:파란|파랑|푸른).*우산/);
          assert.match(translated, /따뜻한.*(?:코트|외투)/);
          assert.match(translated, /역/);
          assert.match(translated, /오후.*(?:3시|세 시)/);
          assert.match(translated, /여행/);
          assert.doesNotMatch(translated, /[\u3040-\u30ff]/u);
          assert.ok(revisions.some((v) => !v.final), "Real translation must stream partials");
          assert.deepEqual(revisions.map((v) => v.revision), [...new Set(revisions.map((v) => v.revision))].sort((a, b) => a - b));
          assert.ok(final.parts.length > 1, "Real final must exercise timed splitting at this viewport");
          assert.equal(final.parts.map((part) => part.text).join(""), translated.trim(), "Every final character must be displayed");
          assert.ok(revisions.every((v) => v.parts.every((part) => part.twoLines)));
          assert.ok(revisions.every((v) => translated.startsWith(v.translation)), "Partials must update the same translation");
          samples.push({ repetition, sessionId: final.sessionId, utteranceId: final.utteranceId,
            firstInference: repetition === 0, revisionCount: revisions.length, finalRevision: final.revision,
            characterCount: translated.trim().length, qualityChecks: true, allCharactersDisplayed: true,
            parts: final.parts.map(({ text, ...part }) => part) });
        }
        const rows = await finishTrace(); finishTrace = undefined;
        for (const sample of samples) {
          const parts = rows.filter((r) => r.type === "part" && r.sessionId === sample.sessionId
            && r.utteranceId === sample.utteranceId && r.revision === sample.finalRevision);
          assert.equal(parts.length, sample.parts.length);
          assert.ok(parts.every((part) => part.paintAtMs !== null), "Every real final part must have a covering Chromium Paint");
          sample.parts = parts;
          sample.partialPaints = rows.filter((r) => r.type === "part" && r.sessionId === sample.sessionId
            && r.utteranceId === sample.utteranceId && !r.final && r.paintAtMs !== null).length;
          assert.ok(sample.partialPaints > 0);
        }
        const receipts = metrics.filter((m) => m.metric === "receipt" && m.sessionId === captureStatus.sessionId);
        const report = { browser: context.browser().version(), nativeCapture: true, realLocalModels: true,
          speech: "macOS Samantha 165 wpm; blue umbrella, warm coat, station, afternoon three, trip", viewport: page.viewportSize(),
          wavSha256: createHash("sha256").update(clips[0]).digest("hex"), samples,
          maxPendingAudioMs: Math.max(0, ...receipts.map((r) => r.pendingAudioMs)),
          droppedFrames: receipts.at(-1)?.droppedFrames, droppedUtterances: receipts.at(-1)?.droppedUtterances,
          listening: "not verified; UI tools expose no speaker audio" };
        assert.ok(report.maxPendingAudioMs <= 8000);
        assert.equal(report.droppedFrames, 0); assert.equal(report.droppedUtterances, 0);
        await writeFile("docs/verification/latency/stream-long.json", `${JSON.stringify(report, null, 2)}\n`);
        console.log(JSON.stringify(report));
        measured = true; passed = true;
      }
      if (command === "measure") {
        assert.ok(paintPhase && finishTrace);
        const { captureStatus } = await worker.evaluate(() => chrome.storage.session.get("captureStatus"));
        assert.equal(captureStatus.state, "capturing");
        const samples = [];
        for (let repetition = -1; repetition < 3; repetition++) {
          for (let clip = 0; clip < (repetition < 0 ? 1 : clips.length); clip++) {
            const start = metrics.length;
            await page.locator("audio").evaluate(async (element, index) => {
              element.src = `/${index}.wav`; await element.play();
            }, clip);
            const deadline = Date.now() + 90000;
            while (!metrics.slice(start).some((m) => m.metric === "caption" && m.final)) {
              assert.ok(Date.now() < deadline, "No real final caption before deadline");
              await page.waitForTimeout(50);
            }
            const captions = metrics.slice(start).filter((m) => m.metric === "caption");
            assert.equal(new Set(captions.map((m) => m.utteranceId)).size, 1);
            const final = captions.find((m) => m.final);
            const text = await page.locator("#interpreter-captions .cue").textContent();
            assert.match(text, /[가-힣]/);
            console.log(JSON.stringify({ review: [repetition, clip], text }));
            samples.push({ repetition, clip, sessionId: final.sessionId, utteranceId: final.utteranceId,
              audioEndMs: final.audioEndMs, originMs: final.originMs, asrMs: final.asrMs });
            await page.waitForTimeout(250);
          }
        }
        const rows = await finishTrace(); finishTrace = undefined;
        for (const sample of samples) {
          const revisions = rows.filter((r) => r.sessionId === sample.sessionId && r.utteranceId === sample.utteranceId && r.type === "caption");
          const first = revisions.find((r) => r.paintAtMs !== null);
          const final = revisions.find((r) => r.final);
          sample.firstPaintMs = first ? first.paintAtMs - sample.originMs - sample.audioEndMs : null;
          sample.finalPaintMs = final?.paintAtMs !== null && final?.paintAtMs !== undefined
            ? final.paintAtMs - sample.originMs - sample.audioEndMs : null;
          sample.revisions = revisions;
        }
        const receipts = metrics.filter((m) => m.metric === "receipt" && m.sessionId === captureStatus.sessionId);
        paintReport = { phase: paintPhase, browser: context.browser().version(),
          measurement: "Chromium main-frame Paint covering cue bounds after matching revision DOM mark; not rAF or server emission",
          baseline: "before: 500ms silence, partial delivery withheld; after: 300ms silence, partial delivery; same prepared models/prompt/streaming requests",
          coldComparison: "none; cached models, separate first inference sample (repetition -1)",
          wavSha256: clips.map((clip) => createHash("sha256").update(clip).digest("hex")), samples,
          maxPendingAudioMs: Math.max(0, ...receipts.map((r) => r.pendingAudioMs)),
          droppedFrames: receipts.at(-1)?.droppedFrames, droppedUtterances: receipts.at(-1)?.droppedUtterances };
        for (const field of ["firstPaintMs", "finalPaintMs"]) {
          const values = samples.filter((s) => s.repetition >= 0 && s[field] !== null).map((s) => s[field]).sort((a, b) => a - b);
          paintReport[field] = { n: values.length, p50Ms: values[Math.ceil(values.length * .5) - 1] ?? null,
            p95Ms: values[Math.ceil(values.length * .95) - 1] ?? null };
        }
        await writeFile(`${profile}/paint-report.json`, `${JSON.stringify(paintReport, null, 2)}\n`);
        console.log(JSON.stringify(paintReport));
        assert.equal(paintReport.firstPaintMs.n, 6);
        assert.equal(paintReport.finalPaintMs.n, 6);
        assert.ok(paintReport.maxPendingAudioMs <= 8000);
        assert.equal(paintReport.droppedFrames, 0); assert.equal(paintReport.droppedUtterances, 0);
        if (paintPhase === "after") {
          const before = JSON.parse(await readFile("docs/verification/latency/paint-before.json", "utf8"));
          assert.deepEqual(paintReport.wavSha256, before.wavSha256);
          assert.ok(paintReport.firstPaintMs.p50Ms < before.firstPaintMs.p50Ms);
        }
        await writeFile(`docs/verification/latency/paint-${paintPhase}.json`, `${JSON.stringify(paintReport, null, 2)}\n`);
        measured = true; passed = true;
      }
      if (command === "play") { await page.locator("#play").click(); console.log("Generated speech playing"); }
      if (command === "check") {
        const status = await worker.evaluate(() => chrome.storage.session.get("captureStatus"));
        const captured = await worker.evaluate(() => chrome.tabCapture.getCapturedTabs());
        const text = await page.locator("#interpreter-captions .cue").textContent({ timeout: 1000 }).catch(() => "");
        console.log(JSON.stringify({ status, captured, text }));
      }
      if (command === "stopped") {
        const status = await worker.evaluate(() => chrome.storage.session.get("captureStatus"));
        const captured = await worker.evaluate(() => chrome.tabCapture.getCapturedTabs());
        const offscreen = await worker.evaluate(() => chrome.runtime.getContexts({ contextTypes: ["OFFSCREEN_DOCUMENT"] }));
        assert.equal(status.captureStatus.state, "idle");
        assert.equal(captured.some((tab) => tab.status === "active"), false);
        assert.equal(offscreen.length, 0);
        assert.equal(await page.locator("#interpreter-captions").count(), 0);
        stopped = true;
        console.log(JSON.stringify({ stopped: true, captionHosts: 0, offscreenContexts: 0, status, captured }));
      }
      if (command === "accept") {
        const cue = page.locator("#interpreter-captions .cue");
        await cue.waitFor({ timeout: 90000 });
        const text = await cue.textContent();
        assert.match(text, /[가-힣]/);
        const status = await worker.evaluate(() => chrome.storage.session.get("captureStatus"));
        assert.equal(status.captureStatus.state, "capturing");
        const captured = await worker.evaluate(() => chrome.tabCapture.getCapturedTabs());
        assert.equal(captured[0]?.status, "active");
        await mkdir("docs/verification/local", { recursive: true });
        await page.screenshot({ path: paintPhase ? `docs/verification/latency/paint-${paintPhase}.png` : "docs/verification/local/normal.png" });
        passed = true;
        console.log(JSON.stringify({ realTabCapture: true, realLocalModels: true, generatedSpeech: true, text, status }));
      }
    } catch (error) { failed = true; console.log(JSON.stringify({ error: String(error) })); }
  }
} finally {
  input?.close();
  process.stdin.pause();
  if (finishTrace) await finishTrace().catch(() => {});
  await context?.close();
  if (companion?.pid && companion.exitCode === null) {
    const exited = once(companion, "exit");
    companion.kill("SIGINT");
    await exited;
  }
  await new Promise((closed) => fixture.close(closed));
  if (failed || !passed || !stopped || (instrumented && !measured)) process.exitCode = 1;
}
