// Actual tabCapture + both local models. Invoke the native toolbar and Start.
import assert from "node:assert/strict";
import { execFileSync, spawn } from "node:child_process";
import { once } from "node:events";
import { mkdir, mkdtemp, readFile } from "node:fs/promises";
import { createServer } from "node:http";
import { resolve } from "node:path";
import { createInterface } from "node:readline";
import { chromium } from "playwright";

await mkdir(".ralph", { recursive: true });
const profile = await mkdtemp(resolve(".ralph/local-browser-"));
execFileSync("say", ["-v", "Samantha", "-r", "165", "-o", `${profile}/speech.aiff`,
  "The weather is sunny today. We will walk to the park after lunch."]);
execFileSync("afconvert", ["-f", "WAVE", "-d", "LEI16@24000", "-c", "1", `${profile}/speech.aiff`, `${profile}/speech.wav`]);
const audio = await readFile(`${profile}/speech.wav`);
const fixture = createServer((request, response) => {
  if (request.url === "/speech.wav") { response.setHeader("Content-Type", "audio/wav"); response.end(audio); return; }
  response.setHeader("Content-Type", "text/html");
  response.end(`<!doctype html><html lang="en"><meta charset="utf-8"><title>Local speech acceptance</title>
    <style>body{margin:0;background:#446879;color:white;font:24px system-ui}main{padding:48px}audio{width:80%}</style>
    <main><h1>Generated English speech</h1><p>A non-sensitive weather and park sentence, generated by macOS.</p>
    <audio controls src="/speech.wav"></audio><button id="play">Play speech</button></main>
    <script>document.querySelector('#play').onclick=()=>{const a=document.querySelector('audio');a.currentTime=0;a.play()};</script></html>`);
});
let context;
let companion;
let input;
let log = "";
let passed = false;
try {
  await new Promise((ready) => fixture.listen(8766, "127.0.0.1", ready));
  const extension = resolve("extension/dist");
  context = await chromium.launchPersistentContext(profile, {
    channel: "chromium", headless: false, viewport: { width: 1280, height: 800 },
    args: [`--disable-extensions-except=${extension}`, `--load-extension=${extension}`],
  });
  const worker = context.serviceWorkers()[0] ?? await context.waitForEvent("serviceworker");
  const extensionId = new URL(worker.url()).host;
  companion = spawn("uv", ["run", "--locked", "--extra", "local", "uvicorn", "server.app:app",
    "--host", "127.0.0.1", "--port", "8765", "--ws-max-size", "4096", "--ws-max-queue", "8"], {
    env: { ...process.env, INTERPRETER_EXTENSION_ID: extensionId, HF_HUB_OFFLINE: "1", TRANSFORMERS_OFFLINE: "1" },
    stdio: ["ignore", "pipe", "pipe"],
  });
  companion.stdout.on("data", (chunk) => { log += chunk; });
  companion.stderr.on("data", (chunk) => { log += chunk; });
  await new Promise((ready, reject) => {
    const timeout = setTimeout(() => reject(new Error(`Companion startup timed out: ${log}`)), 20000);
    companion.once("error", reject);
    companion.stderr.on("data", () => {
      if (log.includes("Uvicorn running")) { clearTimeout(timeout); ready(); }
    });
  });
  const page = context.pages()[0];
  await page.goto("http://127.0.0.1:8766/");
  console.log(JSON.stringify({ ready: true, browser: context.browser().version(), extensionId,
    instructions: "Native Extensions toolbar → Interpreter → Start; close popup. Enter play, check, or exit." }));
  input = createInterface({ input: process.stdin });
  for await (const command of input) {
    try {
      if (command === "exit") break;
      if (command === "play") { await page.locator("#play").click(); console.log("Generated speech playing"); }
      if (command === "check") {
        const status = await worker.evaluate(() => chrome.storage.session.get("captureStatus"));
        const captured = await worker.evaluate(() => chrome.tabCapture.getCapturedTabs());
        const text = await page.locator("#interpreter-captions .cue").textContent({ timeout: 1000 }).catch(() => "");
        console.log(JSON.stringify({ status, captured, text }));
      }
      if (command === "accept") {
        const cue = page.locator("#interpreter-captions .cue");
        await cue.waitFor({ timeout: 90000 });
        const text = await cue.textContent();
        assert.match(text, /[가-힣]/);
        const status = await worker.evaluate(() => chrome.storage.session.get("captureStatus"));
        assert.equal(status.captureStatus.state, "capturing");
        const captured = await worker.evaluate(() => chrome.tabCapture.getCapturedTabs());
        assert.equal(captured[0]?.status, "active");
        await mkdir("docs/verification/local", { recursive: true });
        await page.screenshot({ path: "docs/verification/local/normal.png" });
        passed = true;
        console.log(JSON.stringify({ realTabCapture: true, realLocalModels: true, generatedSpeech: true, text, status }));
      }
    } catch (error) { console.log(JSON.stringify({ error: String(error) })); }
  }
} finally {
  input?.close();
  process.stdin.pause();
  await context?.close();
  if (companion?.pid && companion.exitCode === null) {
    const exited = once(companion, "exit");
    companion.kill("SIGINT");
    await exited;
  }
  await new Promise((closed) => fixture.close(closed));
  if (!passed) process.exitCode = 1;
}
