// Explicit local fixture generation only. Requires the already installed macOS voices.
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { createServer } from "node:http";
import { chromium } from "playwright";
import { retimeSpeechVideo } from "./retime.mjs";

const clips = [
  { language: "ja", voice: "Kyoko", text: "今日は会議をしません。明日の午後三時に駅で会いましょう。予約は取り消さないでください。", koreanMeaning: "오늘은 회의하지 않습니다. 내일 오후 세 시에 역에서 만납시다. 예약을 취소하지 마세요.", tagHz: 6500 },
  { language: "en", voice: "Samantha", text: "We will not meet today. Let's meet at the station tomorrow at three in the afternoon. Please do not cancel the reservation.", koreanMeaning: "오늘은 만나지 않습니다. 내일 오후 세 시에 역에서 만납시다. 예약을 취소하지 마세요.", tagHz: 9000 },
];
const scratch = ".ralph/media-framework/video-speech-generation";
await mkdir(scratch, { recursive: true });
for (const clip of clips) execFileSync("/usr/bin/say", ["-v", clip.voice, "-r", "180", "--file-format=WAVE", "--data-format=LEI16@48000", "-o", `${scratch}/${clip.language}.wav`, clip.text]);
const server = createServer(async (request, response) => {
  const language = request.url.slice(1).replace(".wav", "");
  if (clips.some((clip) => clip.language === language)) {
    response.setHeader("Content-Type", "audio/wav"); response.end(await readFile(`${scratch}/${language}.wav`));
  } else { response.setHeader("Content-Type", "text/html"); response.end("<button>Generate synthetic speech video</button>"); }
});
await new Promise((done) => server.listen(0, "127.0.0.1", done));
let browser;
try {
  browser = await chromium.launch({ channel: "chromium", headless: true, ignoreDefaultArgs: ["--mute-audio"] });
  for (const clip of clips) {
    const page = await browser.newPage();
    await page.goto(`http://127.0.0.1:${server.address().port}`);
    await page.getByRole("button").click();
    const result = await page.evaluate(async (clip) => {
      const context = new AudioContext({ sampleRate: 48000 }); await context.resume();
      const speech = await context.decodeAudioData(await (await fetch(`/${clip.language}.wav`)).arrayBuffer());
      const samples = speech.getChannelData(0);
      const peak = samples.reduce((max, value) => Math.max(max, Math.abs(value)), 0);
      if (peak < 0.01 || speech.duration < 3) throw new Error('Installed voice did not produce speech');
      const canvas = document.createElement('canvas'); canvas.width = 320; canvas.height = 180;
      let frame = 0;
      const draw = () => { const image = canvas.getContext('2d'); image.fillStyle = '#426'; image.fillRect(0, 0, 320, 180);
        image.fillStyle = 'white'; image.fillText(`${clip.language} synthetic speech / ${frame++}`, 20, 70); };
      draw(); const timer = setInterval(draw, 100);
      const source = context.createBufferSource(); source.buffer = speech; source.loop = true;
      const gain = context.createGain(); gain.gain.value = 0.18 / peak;
      const destination = context.createMediaStreamDestination(); source.connect(gain).connect(destination);
      const tag = context.createOscillator(); tag.frequency.value = clip.tagHz;
      const tagGain = context.createGain(); tagGain.gain.value = 0.06; tag.connect(tagGain).connect(destination);
      const stream = canvas.captureStream(10); stream.addTrack(destination.stream.getAudioTracks()[0]);
      const recorder = new MediaRecorder(stream, { mimeType: 'video/webm;codecs=vp8,opus', audioBitsPerSecond: 128000 });
      const parts = []; recorder.ondataavailable = ({ data }) => parts.push(data);
      const stopped = new Promise((done) => { recorder.onstop = done; });
      recorder.start(); source.start(); tag.start();
      await new Promise((done) => setTimeout(done, 24000)); recorder.stop(); await stopped;
      clearInterval(timer); source.stop(); tag.stop(); for (const track of stream.getTracks()) track.stop(); await context.close();
      const bytes = new Uint8Array(await new Blob(parts).arrayBuffer());
      let binary = ''; for (const byte of bytes) binary += String.fromCharCode(byte);
      return { base64: btoa(binary), speechDurationSeconds: speech.duration, originalSpeechPeak: peak };
    }, clip);
    const bytes = retimeSpeechVideo(Buffer.from(result.base64, "base64")); assert.ok(bytes.length > 10000);
    await writeFile(`tests/fixtures/video-speech/${clip.language}.webm`, bytes);
    clip.speechDurationSeconds = result.speechDurationSeconds;
    clip.originalSpeechPeak = result.originalSpeechPeak;
    clip.bytes = bytes.length; clip.sha256 = createHash("sha256").update(bytes).digest("hex");
    await page.close();
  }
  await writeFile("tests/fixtures/video-speech/manifest.json", `${JSON.stringify({ provenance: "Local macOS say synthetic speech; no user recordings. Generated by node tests/fixtures/video-speech/generate.mjs; no voice installation.", video: "24 seconds, 320x180, VP8/Opus; normalized speech peak 0.18 plus continuous 0.06 isolation tag; repeated speech", clips }, null, 2)}\n`);
  console.log(JSON.stringify(clips));
} finally { await browser?.close(); await new Promise((done) => server.close(done)); }
